export declare const get: import("convex/server").RegisteredQuery<"public", {
    runId: string;
    ownerId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"subagentRuns">;
    _creationTime: number;
    label?: string | undefined;
    model?: string | undefined;
    startedAt?: number | undefined;
    outcome?: {
        error?: string | undefined;
        reason?: string | undefined;
        text?: ArrayBuffer | undefined;
        status: "timeout" | "error" | "abort" | "ok";
    } | undefined;
    workspaceDir?: string | undefined;
    controllerSessionKey?: string | undefined;
    requesterOrigin?: ArrayBuffer | undefined;
    runTimeoutSeconds?: number | undefined;
    spawnMode?: "run" | "session" | undefined;
    sessionStartedAt?: number | undefined;
    accumulatedRuntimeMs?: number | undefined;
    endedAt?: number | undefined;
    archiveAtMs?: number | undefined;
    cleanupCompletedAt?: number | undefined;
    cleanupHandled?: boolean | undefined;
    suppressAnnounceReason?: "steer-restart" | "killed" | undefined;
    expectsCompletionMessage?: boolean | undefined;
    announceRetryCount?: number | undefined;
    lastAnnounceRetryAt?: number | undefined;
    endedReason?: string | undefined;
    wakeOnDescendantSettle?: boolean | undefined;
    frozenResultText?: ArrayBuffer | undefined;
    frozenResultCapturedAt?: number | undefined;
    fallbackFrozenResultText?: ArrayBuffer | undefined;
    fallbackFrozenResultCapturedAt?: number | undefined;
    endedHookEmittedAt?: number | undefined;
    completionAnnouncedAt?: number | undefined;
    attachmentsDir?: string | undefined;
    attachmentsRootDir?: string | undefined;
    retainAttachmentsOnKeep?: boolean | undefined;
    task: ArrayBuffer;
    runId: string;
    createdAt: number;
    ownerId: string;
    cleanup: "delete" | "keep";
    childSessionKey: string;
    requesterSessionKey: string;
    requesterDisplayKey: string;
} | null>>;
export declare const getByChildSessionKey: import("convex/server").RegisteredQuery<"public", {
    ownerId: string;
    childSessionKey: string;
}, Promise<{
    _id: import("convex/values").GenericId<"subagentRuns">;
    _creationTime: number;
    label?: string | undefined;
    model?: string | undefined;
    startedAt?: number | undefined;
    outcome?: {
        error?: string | undefined;
        reason?: string | undefined;
        text?: ArrayBuffer | undefined;
        status: "timeout" | "error" | "abort" | "ok";
    } | undefined;
    workspaceDir?: string | undefined;
    controllerSessionKey?: string | undefined;
    requesterOrigin?: ArrayBuffer | undefined;
    runTimeoutSeconds?: number | undefined;
    spawnMode?: "run" | "session" | undefined;
    sessionStartedAt?: number | undefined;
    accumulatedRuntimeMs?: number | undefined;
    endedAt?: number | undefined;
    archiveAtMs?: number | undefined;
    cleanupCompletedAt?: number | undefined;
    cleanupHandled?: boolean | undefined;
    suppressAnnounceReason?: "steer-restart" | "killed" | undefined;
    expectsCompletionMessage?: boolean | undefined;
    announceRetryCount?: number | undefined;
    lastAnnounceRetryAt?: number | undefined;
    endedReason?: string | undefined;
    wakeOnDescendantSettle?: boolean | undefined;
    frozenResultText?: ArrayBuffer | undefined;
    frozenResultCapturedAt?: number | undefined;
    fallbackFrozenResultText?: ArrayBuffer | undefined;
    fallbackFrozenResultCapturedAt?: number | undefined;
    endedHookEmittedAt?: number | undefined;
    completionAnnouncedAt?: number | undefined;
    attachmentsDir?: string | undefined;
    attachmentsRootDir?: string | undefined;
    retainAttachmentsOnKeep?: boolean | undefined;
    task: ArrayBuffer;
    runId: string;
    createdAt: number;
    ownerId: string;
    cleanup: "delete" | "keep";
    childSessionKey: string;
    requesterSessionKey: string;
    requesterDisplayKey: string;
} | null>>;
export declare const listByRequester: import("convex/server").RegisteredQuery<"public", {
    ownerId: string;
    requesterSessionKey: string;
}, Promise<{
    _id: import("convex/values").GenericId<"subagentRuns">;
    _creationTime: number;
    label?: string | undefined;
    model?: string | undefined;
    startedAt?: number | undefined;
    outcome?: {
        error?: string | undefined;
        reason?: string | undefined;
        text?: ArrayBuffer | undefined;
        status: "timeout" | "error" | "abort" | "ok";
    } | undefined;
    workspaceDir?: string | undefined;
    controllerSessionKey?: string | undefined;
    requesterOrigin?: ArrayBuffer | undefined;
    runTimeoutSeconds?: number | undefined;
    spawnMode?: "run" | "session" | undefined;
    sessionStartedAt?: number | undefined;
    accumulatedRuntimeMs?: number | undefined;
    endedAt?: number | undefined;
    archiveAtMs?: number | undefined;
    cleanupCompletedAt?: number | undefined;
    cleanupHandled?: boolean | undefined;
    suppressAnnounceReason?: "steer-restart" | "killed" | undefined;
    expectsCompletionMessage?: boolean | undefined;
    announceRetryCount?: number | undefined;
    lastAnnounceRetryAt?: number | undefined;
    endedReason?: string | undefined;
    wakeOnDescendantSettle?: boolean | undefined;
    frozenResultText?: ArrayBuffer | undefined;
    frozenResultCapturedAt?: number | undefined;
    fallbackFrozenResultText?: ArrayBuffer | undefined;
    fallbackFrozenResultCapturedAt?: number | undefined;
    endedHookEmittedAt?: number | undefined;
    completionAnnouncedAt?: number | undefined;
    attachmentsDir?: string | undefined;
    attachmentsRootDir?: string | undefined;
    retainAttachmentsOnKeep?: boolean | undefined;
    task: ArrayBuffer;
    runId: string;
    createdAt: number;
    ownerId: string;
    cleanup: "delete" | "keep";
    childSessionKey: string;
    requesterSessionKey: string;
    requesterDisplayKey: string;
}[]>>;
export declare const put: import("convex/server").RegisteredMutation<"public", {
    record: any;
    ownerId: string;
}, Promise<void>>;
export declare const markCompleted: import("convex/server").RegisteredMutation<"public", {
    error?: string | undefined;
    endedHookEmittedAt?: number | undefined;
    runId: string;
    reason: string;
    outcome: any;
    ownerId: string;
    endedAt: number;
}, Promise<{
    _id: import("convex/values").GenericId<"subagentRuns">;
    _creationTime: number;
    label?: string | undefined;
    model?: string | undefined;
    startedAt?: number | undefined;
    outcome?: {
        error?: string | undefined;
        reason?: string | undefined;
        text?: ArrayBuffer | undefined;
        status: "timeout" | "error" | "abort" | "ok";
    } | undefined;
    workspaceDir?: string | undefined;
    controllerSessionKey?: string | undefined;
    requesterOrigin?: ArrayBuffer | undefined;
    runTimeoutSeconds?: number | undefined;
    spawnMode?: "run" | "session" | undefined;
    sessionStartedAt?: number | undefined;
    accumulatedRuntimeMs?: number | undefined;
    endedAt?: number | undefined;
    archiveAtMs?: number | undefined;
    cleanupCompletedAt?: number | undefined;
    cleanupHandled?: boolean | undefined;
    suppressAnnounceReason?: "steer-restart" | "killed" | undefined;
    expectsCompletionMessage?: boolean | undefined;
    announceRetryCount?: number | undefined;
    lastAnnounceRetryAt?: number | undefined;
    endedReason?: string | undefined;
    wakeOnDescendantSettle?: boolean | undefined;
    frozenResultText?: ArrayBuffer | undefined;
    frozenResultCapturedAt?: number | undefined;
    fallbackFrozenResultText?: ArrayBuffer | undefined;
    fallbackFrozenResultCapturedAt?: number | undefined;
    endedHookEmittedAt?: number | undefined;
    completionAnnouncedAt?: number | undefined;
    attachmentsDir?: string | undefined;
    attachmentsRootDir?: string | undefined;
    retainAttachmentsOnKeep?: boolean | undefined;
    task: ArrayBuffer;
    runId: string;
    createdAt: number;
    ownerId: string;
    cleanup: "delete" | "keep";
    childSessionKey: string;
    requesterSessionKey: string;
    requesterDisplayKey: string;
} | null>>;
export declare const remove: import("convex/server").RegisteredMutation<"public", {
    runId: string;
    ownerId: string;
}, Promise<boolean>>;
//# sourceMappingURL=subagents.d.ts.map